"""added usernmae

Revision ID: 627eabbe3973
Revises: 58a78de6ac3a
Create Date: 2024-01-30 12:30:01.857989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627eabbe3973'
down_revision = '58a78de6ac3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
