"""added unique email

Revision ID: 766434bcbeac
Revises: 
Create Date: 2024-02-01 11:08:20.851248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766434bcbeac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Car_Infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('general_info', sa.String(), nullable=False),
    sa.Column('engine_info', sa.String(), nullable=True),
    sa.Column('light_info', sa.String(), nullable=True),
    sa.Column('wheel_info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Car_Infos'))
    )
    op.create_table('Maintenance_Infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rec_oil_service', sa.String(), nullable=True),
    sa.Column('rec_oil_type', sa.String(), nullable=True),
    sa.Column('inputed_oil_service', sa.String(), nullable=True),
    sa.Column('rec_tire_roto', sa.String(), nullable=True),
    sa.Column('inputed_tire_roto', sa.String(), nullable=True),
    sa.Column('rec_tire_psi', sa.String(), nullable=True),
    sa.Column('rec_break_fluid_service', sa.String(), nullable=True),
    sa.Column('inputed_break_fluid_service', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Maintenance_Infos'))
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Users')),
    sa.UniqueConstraint('email', name=op.f('uq_Users_email'))
    )
    op.create_table('Saved_Cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('car_info_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_info_id'], ['Car_Infos.id'], name=op.f('fk_Saved_Cars_car_info_id_Car_Infos')),
    sa.ForeignKeyConstraint(['maintenance_info_id'], ['Maintenance_Infos.id'], name=op.f('fk_Saved_Cars_maintenance_info_id_Maintenance_Infos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Saved_Cars'))
    )
    op.create_table('Garages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('saved_car_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saved_car_id'], ['Saved_Cars.id'], name=op.f('fk_Garages_saved_car_id_Saved_Cars')),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name=op.f('fk_Garages_user_id_Users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Garages'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Garages')
    op.drop_table('Saved_Cars')
    op.drop_table('Users')
    op.drop_table('Maintenance_Infos')
    op.drop_table('Car_Infos')
    # ### end Alembic commands ###
