"""added summary

Revision ID: a230dc39e717
Revises: 82ded77544ac
Create Date: 2024-02-12 11:58:28.433467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a230dc39e717'
down_revision = '82ded77544ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Car_Infos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Car_Infos', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
