"""fixed error

Revision ID: a5aefab62148
Revises: 627eabbe3973
Create Date: 2024-01-30 12:35:09.911287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5aefab62148'
down_revision = '627eabbe3973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Saved_Cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_info_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_info_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_Saved_Cars_car_info_id_Car_Infos'), 'Car_Infos', ['car_info_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_Saved_Cars_maintenance_info_id_Maintenance_Infos'), 'Maintenance_Infos', ['maintenance_info_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Saved_Cars', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Saved_Cars_maintenance_info_id_Maintenance_Infos'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_Saved_Cars_car_info_id_Car_Infos'), type_='foreignkey')
        batch_op.drop_column('maintenance_info_id')
        batch_op.drop_column('car_info_id')

    # ### end Alembic commands ###
