"""added oil mileage

Revision ID: a72bb6678070
Revises: 766434bcbeac
Create Date: 2024-02-02 09:43:53.844305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72bb6678070'
down_revision = '766434bcbeac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Maintenance_Infos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mileage_oil_service', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Maintenance_Infos', schema=None) as batch_op:
        batch_op.drop_column('mileage_oil_service')

    # ### end Alembic commands ###
